In [1]:
import numpy as np

In [2]:
z = np.array([1,2,3,4,5])
print(z)
print(type(z))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
c = np.array([[1,2,3], [4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((3,2), 5) #for matrix with single value

array([[5, 5],
       [5, 5],
       [5, 5]])

In [7]:
np.eye(4) #for identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#always choses between 0 and 1
z = np.random.random((5,4))
print(z)

[[0.60817193 0.9952939  0.14342474 0.65120087]
 [0.88068336 0.44915286 0.04689837 0.66815267]
 [0.45969034 0.92871797 0.442764   0.93005027]
 [0.76124247 0.70885871 0.42454491 0.63613327]
 [0.9610324  0.59635156 0.61724901 0.80050314]]


In [9]:
print(z[:,1])

[0.9952939  0.44915286 0.92871797 0.70885871 0.59635156]


In [10]:
np.zeros((3,3), dtype = np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [11]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print("add : ", end = " ")
print(np.add(x,y))

print("sub : ", end = " ")
print(np.subtract(x,y))

print("multi : ")
print(np.multiply(x,y))

print("divi : ")
print(np.divide(x,y))

print("sqrt : ")
print(np.sqrt(x))

add :  [[ 6  8]
 [10 12]]
sub :  [[-4 -4]
 [-4 -4]]
multi : 
[[ 5 12]
 [21 32]]
divi : 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
sqrt : 
[[1.         1.41421356]
 [1.73205081 2.        ]]


- axis = 0 means column and axis = 1 means row

### stacking of array

In [20]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
b = b**2
print(a)
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [21]:
a = np.stack((a,b),axis=0)

In [22]:
a

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [15]:
a = a.reshape(2,4)

In [16]:
a

array([[ 1,  1,  2,  4],
       [ 3,  9,  4, 16]])

## Random Generator

In [17]:
a = np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [18]:
np.random.shuffle(a)
print(a)

[12  9 14 11  6  8  5 13 10  7]


In [19]:
a = np.random.randn(2,3)
b = np.random.randint(2,8,3)

print(a)
print(b)

ele = np.random.choice([1,3,5,7,9])
print(ele)

[[ 1.4750323  -0.20266011  0.21472201]
 [ 1.28968526  0.38560986  1.50318031]]
[7 2 7]
1


- for generating a single series while random use "np.random.seed( value )"