In [1]:
import numpy as np

- for min,max median of array data from the nupy array

In [2]:
a = np.random.randint(2,15,(3,5))
print(a)
print()
print(np.min(a, axis = 0))
print(np.min(a, axis = 1))
print(np.max(a, axis = 0))
print(np.max(a, axis = 1))

[[ 3  9  3  7  8]
 [ 7  2  6 10  8]
 [ 8 13  7 11 10]]

[3 2 3 7 8]
[3 2 7]
[ 8 13  7 11 10]
[ 9 10 13]


- mean, median, average works the same way

In [5]:
c = np.array([1,5,2,8,4])
print(np.median(c))
print(np.mean(c))

# weights
w = np.array([5,9,7,6,4])
print(np.average(c,weights=w))

#Standard Deviation
u = np.mean(c)
mystd = np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

4.0
4.0
4.129032258064516
2.449489742783178


In [7]:
dev = np.std(c)
print(dev)

print(mystd**2)
print(np.var(c))

2.449489742783178
5.999999999999999
6.0


In [51]:
a = np.random.randint(0,15, size=(30,1))

In [55]:
a.resize((6,5))

In [56]:
a

array([[13, 12,  5,  3,  1],
       [ 2,  9,  0,  9, 11],
       [12, 13,  5, 10, 12],
       [ 8,  2, 10,  4,  7],
       [ 3,  9,  0,  9,  9],
       [ 1, 11,  0,  7,  2]])

In [61]:
a = a.reshape((-1,5))

In [62]:
a

array([[13, 12,  5,  3,  1],
       [ 2,  9,  0,  9, 11],
       [12, 13,  5, 10, 12],
       [ 8,  2, 10,  4,  7],
       [ 3,  9,  0,  9,  9],
       [ 1, 11,  0,  7,  2]])

In [68]:
a = np.arange(1,17).reshape(4,4)
b = np.arange(17,33).reshape(4,4)

In [69]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [70]:
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [71]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [72]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [73]:
np.concatenate((a,b), axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [74]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])